env:
  global:
    - secure: kERfGEJxywTI3AvAsOCcjQBuxrAiJ7aOWooLmtxy8QWzNkVUlhY2A5xGWCqyKunMmjj9+cJ2FtrejYDo9FcXtmL2MlU0M6YZ1vLCeYTMsxMurZNXH0o64X0pFRsYAxR/uYgiZKujXBTcXiRlKkBd2G+aVetKPUl3rTi3nrejlto=
    - Features=use-mock-routing
os:
  - linux
  - osx
language: rust
rust:
  - nightly
sudo: false
cache:
  cargo: true
install:
  - ls && git clone https://github.com/maidsafe/safe_core.git && cd safe_core  && ls
  - cargo build --release --verbose
after_install:
  - cd .. && ls
