env:
  global:
    - secure: kERfGEJxywTI3AvAsOCcjQBuxrAiJ7aOWooLmtxy8QWzNkVUlhY2A5xGWCqyKunMmjj9+cJ2FtrejYDo9FcXtmL2MlU0M6YZ1vLCeYTMsxMurZNXH0o64X0pFRsYAxR/uYgiZKujXBTcXiRlKkBd2G+aVetKPUl3rTi3nrejlto=
os:
  - linux
language: rust
rust:
  - nightly
python:
  - "2.7"  
sudo: false
cache:
  cargo: true
install:
  - pwd && cd ..
  - curl -sSLO https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/install_libsodium.sh
  - . install_libsodium.sh
  - . $HOME/.nvm/nvm.sh
  - nvm install 5.5.0
  - nvm use 5.5.0
script:
  - git clone https://github.com/maidsafe/safe_core.git && cd safe_core
  - cargo build --release --verbose --features use-mock-routing
  - cp -i target/release/libsafe_core.a $TRAVIS_BUILD_DIR/app/api/ffi
  - cd $TRAVIS_BUILD_DIR && ls
  - node -v
  - python --version
  - npm install
  - npm test
