env:
  global:
    - secure: kERfGEJxywTI3AvAsOCcjQBuxrAiJ7aOWooLmtxy8QWzNkVUlhY2A5xGWCqyKunMmjj9+cJ2FtrejYDo9FcXtmL2MlU0M6YZ1vLCeYTMsxMurZNXH0o64X0pFRsYAxR/uYgiZKujXBTcXiRlKkBd2G+aVetKPUl3rTi3nrejlto=
    - Features=use-mock-routing
os:
  - linux
  - osx
language: rust
rust:
  - nightly
sudo: false
cache:
  cargo: true
install:
  - set evn $SAFE_CORE_REPO_PATH = './safe_core'
  - ls && git clone https://github.com/maidsafe/safe_core.git $SAFE_CORE_REPO_PATH 
  - cd $SAFE_CORE_REPO_PATH && ls 
  - cargo build --release --verbose
after_install:
  - cd .. && ls
